version: '3.8'

services:
  api-prod:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: backend-inv-api-prod
    container_name: backend-api-prod
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/isc_inventory
      - SPRING_DATASOURCE_USERNAME=inventory
      - SPRING_DATASOURCE_PASSWORD=Zp15#kV42wLp@yR6m
      - FRONTEND_URL=https://app.inventory.integritysolutions.com.ec/
      - SERVER_PORT=8080
    depends_on:
      - postgres
    networks:
      - backend-net

  auth-prod:
    build:
      context: .
      dockerfile: auth/Dockerfile
    image: backend-inv-auth-prod
    container_name: backend-auth-prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/isc_inventory
      - SPRING_DATASOURCE_USERNAME=inventory
      - SPRING_DATASOURCE_PASSWORD=Zp15#kV42wLp@yR6m
      - FRONTEND_URL=https://app.inventory.integritysolutions.com.ec/
      - SERVER_PORT=8080
    depends_on:
      - postgres
    networks:
      - backend-net

networks:
  backend-net:
    external: true
    name: app_backend-net
