version: '3.8'

services:
  api-dev:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: backend-inv-api-dev
    container_name: backend-api-dev
    ports:
      - "9091:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/isc_inventory_dev
      - SPRING_DATASOURCE_USERNAME=app_backend
      - SPRING_DATASOURCE_PASSWORD=I@iventory##12345
      - FRONTEND_URL=http://147.93.181.147:8081/
      - SERVER_PORT=8080
    depends_on:
      - postgres
    networks:
      - backend-net

  auth-dev:
    build:
      context: .
      dockerfile: auth/Dockerfile
    image: backend-inv-auth-dev
    container_name: backend-auth-dev
    ports:
      - "9090:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/isc_inventory_dev
      - SPRING_DATASOURCE_USERNAME=inventory
      - SPRING_DATASOURCE_PASSWORD=Zp8#kV42wLp@tR3m
      - FRONTEND_URL=http://147.93.181.147:8081/
      - SERVER_PORT=8080
    depends_on:
      - postgres
    networks:
      - backend-net
