
services:
  api-dev:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: backend-inv-api-dev
    container_name: backend-api-dev
    ports:
      - "9091:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://147.93.181.146:5432/isc_inventory_dev
      - SPRING_DATASOURCE_USERNAME=inventory
      - SPRING_DATASOURCE_PASSWORD=Zp15#kV42wLp@yR6m
      - FRONTEND_URL=http://147.93.181.147:8081/
      - SERVER_PORT=8080
    depends_on:
      - postgres
    networks:
      - backend-net

  isc-inv-auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://isc-inventory-postgres-dev-tpfjds:5432/isc-inventory-db
      - SPRING_DATASOURCE_USERNAME=isc-inventory-admin
      - SPRING_DATASOURCE_PASSWORD=isc-inventory-pass
      - FRONTEND_URL=http://147.93.181.147:8081/
      - SERVER_PORT=8080

    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true